name: test-fortran-macos

# on: [push, pull_request]
on: []

jobs:
  fast_build_release:
    runs-on: [macos-13]
    

    steps:
      - uses: actions/checkout@v4

      - uses: fortran-lang/setup-fortran@v1.6
        id: setup-fortran
        with:
          compiler: gcc 
          version: 11

      # - name: Install GFortran
      #   run: brew install gfortran gcc

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build
          
      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --version
          gfortran-11 --version
          cmake $GITHUB_WORKSPACE -DFORTRAN=ON 

      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --parallel

      - name: Test
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          ls 
          ./bin/fortrantest
